/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Main.GenReport;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.JobAttributes;
import java.awt.PageAttributes;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neo
 */
public class GetReportForm extends javax.swing.JFrame {

    DefaultTableModel model;
    GenReport genRprt;

    public GetReportForm() {
        initComponents();
        this.setTitle("Campulse Result analysis :Report");
        this.setLocationRelativeTo(null);
        genRprt = new GenReport();
        generateTableReport();
        generateClassReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrintPanel = new javax.swing.JPanel();
        PACELOGO = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReport = new javax.swing.JTable();
        overallPanel = new javax.swing.JPanel();
        lFail = new javax.swing.JLabel();
        lFCDCount = new javax.swing.JLabel();
        lFirstClass = new javax.swing.JLabel();
        lSecondClass = new javax.swing.JLabel();
        bPrint = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Result Analaysis");
        setResizable(false);

        PrintPanel.setBackground(new java.awt.Color(255, 255, 255));

        PACELOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pace logo reszed.png"))); // NOI18N

        tableReport.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        tableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableReport.setRowHeight(24);
        jScrollPane1.setViewportView(tableReport);

        overallPanel.setBackground(new java.awt.Color(255, 255, 255));

        lFail.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lFail.setText("Fail : ");

        lFCDCount.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lFCDCount.setText("First Class With Distinction : ");

        lFirstClass.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lFirstClass.setText("First Class : ");

        lSecondClass.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lSecondClass.setText("Second Class :");

        javax.swing.GroupLayout overallPanelLayout = new javax.swing.GroupLayout(overallPanel);
        overallPanel.setLayout(overallPanelLayout);
        overallPanelLayout.setHorizontalGroup(
            overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overallPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFCDCount, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFirstClass, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFail, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSecondClass, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        overallPanelLayout.setVerticalGroup(
            overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overallPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFCDCount)
                    .addComponent(lSecondClass, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFirstClass)
                    .addComponent(lFail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PrintPanelLayout = new javax.swing.GroupLayout(PrintPanel);
        PrintPanel.setLayout(PrintPanelLayout);
        PrintPanelLayout.setHorizontalGroup(
            PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintPanelLayout.createSequentialGroup()
                .addGroup(PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrintPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(overallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PrintPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PrintPanelLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(PACELOGO)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PrintPanelLayout.setVerticalGroup(
            PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrintPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(PACELOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(overallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        bPrint.setText("Print");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addComponent(PrintPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bPrint, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PrintPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPrint)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed

        try {

            Toolkit tkp = PrintPanel.getToolkit();
            PageAttributes pa = new PageAttributes();
            pa.setMedia(PageAttributes.MediaType.A4);
            pa.setOrientationRequested(PageAttributes.OrientationRequestedType.LANDSCAPE);
            PrintJob pjp = tkp.getPrintJob(this, null, null, pa);
            Graphics g = pjp.getGraphics();
            PrintPanel.print(g);
            g.dispose();
            pjp.end();
        } catch (Exception ex) {
            System.out.println("Error : " + ex.getMessage());
            MainForm.logError("Error while Printing");
        }

    }//GEN-LAST:event_bPrintActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PACELOGO;
    private javax.swing.JPanel PrintPanel;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lFCDCount;
    private javax.swing.JLabel lFail;
    private javax.swing.JLabel lFirstClass;
    private javax.swing.JLabel lSecondClass;
    private javax.swing.JPanel overallPanel;
    private javax.swing.JTable tableReport;
    // End of variables declaration//GEN-END:variables

    private void generateTableReport() {
        model = new DefaultTableModel();

        model = genRprt.fillReportTable();
        tableReport.setModel(model);
        tableReport.setAutoCreateRowSorter(true);
        tableReport.getColumn("Subject Names ").setPreferredWidth(380);
        tableReport.getColumn("Registered").setPreferredWidth(90);
        tableReport.getColumn("Pass %").setPreferredWidth(80);
        tableReport.getColumn("Fail").setPreferredWidth(50);
        tableReport.getColumn("FCD").setPreferredWidth(50);
        tableReport.getColumn("FC").setPreferredWidth(50);
        tableReport.getColumn("SC").setPreferredWidth(50);
    }

    private void generateClassReport() {
        genRprt.getAllLabelValues();
        lFCDCount.setText("FIRST CLASS WITH DISTINCTION : " + genRprt.getClassFCD());
        lFirstClass.setText("FIRST CLASS : " + genRprt.getClassFC());
        lSecondClass.setText("SECOND CLASS : " + genRprt.getClassSC());
        lFail.setText("FAIL : " + genRprt.getClassFail());
    }

    public ImageIcon create_Thumbnail(ImageIcon img, int w, int h) {
        BufferedImage bi;
        img = new ImageIcon(img.getImage().getScaledInstance(w, h, BufferedImage.SCALE_FAST));
        bi = new BufferedImage(w, h, BufferedImage.TYPE_INT_BGR);
        Graphics2D g2 = bi.createGraphics();
        g2.drawImage(img.getImage(), 0, 0, null);
        img = null;
        g2.dispose();
        return new ImageIcon(bi);
    }
}
